### ISSUE TITLE
System tray icon shows as "three dots" icon instead of messenger icon

### ISSUE THREAD

**Issue by LeFloatyPancake** [flathub/com.sindresorhus.Caprine#2] opened 2021-09-19 13:44 UTC
The systray icon for caprine shows as a "three dots icon" compared to the appimage version which shows the messenger icon. A couple bug reports have been [reported](https://github.com/sindresorhus/caprine/issues/1693) to the official GitHub page of caprine related to flatpak. Please see image below for reference.
![test](https://user-images.githubusercontent.com/83509112/133929473-c7a42fcc-d887-4e96-b622-34d3e258082b.png)
I tried changing icon themes but it doesn't work. This could be an issue with the systray extension but I don't have another desktop environment to conduct an in-depth troubleshooting (Although others have reported empty icons for other DEs). 

I might be reporting this issue to the wrong party but can anything be done with this?

Thanks so much for maintaining this package.

**Comment by dusansimic** [comment] 2021-09-19 14:15
From my research, this is caused by icon not available in the specified path in the app (due to the way flatpak packages the app). It either needs to be available in the specified path or the path should be changed inside the source of the app. I still haven't found the time to work on this so once I do, I will fix it.

**Comment by LeFloatyPancake** [comment] 2021-10-01 13:48
Good day
I was scrolling through journalctl logs and it seems I have found the issue
```
Oct 01 21:44:14 tahiti appindicatorsupport@rgcjonas.gmail.com[5090]: Caprine1, Impossible to lookup icon for 'Caprine1_1-panel' in path /tmp/.org.chromium.Chromium.WkOZBp
Oct 01 21:44:14 tahiti appindicatorsupport@rgcjonas.gmail.com[5090]: unable to update icon for Caprine1
Oct 01 21:44:14 tahiti appindicatorsupport@rgcjonas.gmail.com[5090]: unable to update icon for Caprine1
```
Tested on gnome with appindicator extension so I have no idea how this looks for other DEs . 

Anyway I did some experimentation and gave Caprine access to the `/tmp` directory via flatseal>filesystem>other files. The icon now shows up but I don't know if this workaround is considered "safe" though. Is it safe?

**Comment by dusansimic** [comment] 2021-10-03 17:30
This should be fixed by the latest commit. Please wait until the package is pushed to Flathub (might take a few hours). The problem was indeed related to the `/tmp` directory so thanks for spotting that @LeFloatyPancake! It's fixed by using the entrypoint script from [com.wire.WireDesktop][wirepkg] package.

I'll close this now but if the issue persists please let me know.

[wirepkg]: https://github.com/flathub/com.wire.WireDesktop/blob/master/entrypoint.sh

**Closed by dusansimic** 2021-10-03 17:30 UTC
